# Generated by Django 5.1.5 on 2025-01-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("founded_year", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dealer_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Sedan", "Sedan"),
                            ("SUV", "SUV"),
                            ("Wagon", "Wagon"),
                            ("Truck", "Truck"),
                            ("Coupe", "Coupe"),
                            ("Moped", "Moped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.DateField()),
                ("horsepower", models.IntegerField(blank=True, null=True)),
                (
                    "fuel_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "car_make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="djangoapp.carmake",
                    ),
                ),
            ],
        ),
    ]
